### ISSUE TITLE
Übersetzung passt noch nicht: "Aktive Timer"

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [BogyMitutoyoCTL/BOGY-App-2023-04#21]
Auch wenn die App auf Englisch eingestellt ist, erscheint hier in der AppBar noch deutscher Text:

![grafik](https://user-images.githubusercontent.com/25632350/228550854-da6516da-a3a1-4178-9115-5f18f5b1085d.png)

**Comment by 5enseiii** [comment]
fixed
