### ISSUE TITLE
Sehr lange Zeitangaben möglich

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [BogyMitutoyoCTL/BOGY-App-2023-04#22]
Beim Anlegen eines Timers sind sehr lange Zeitangaben mit 20 oder mehr Stellen möglich.
Ich würde sagen, dass 3 Stellen reichen (Waschmaschine mit 2 h 36 min = 156 min)

![grafik](https://user-images.githubusercontent.com/25632350/228551343-37de43f4-c67f-49f1-8ab9-3c7b0aca1dc9.png)

**Comment by 5enseiii** [comment]
fixed. man kann nun höchstens 3 ziffern eingeben
