### ISSUE TITLE
Die Textfarbe der AppBar ist schwarz, außer bei Settings

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [BogyMitutoyoCTL/BOGY-App-2023-04#25]
Die Textfarbe der AppBar ist schwarz

![grafik](https://user-images.githubusercontent.com/25632350/228553826-bfc150f0-0255-4dcd-90c9-2bf060defce6.png)

außer bei Settings, dort ist sie weiß:

![grafik](https://user-images.githubusercontent.com/25632350/228553730-749e6dd5-7206-41d1-803b-8b5ae9c3df29.png)

Verwendetes Theme: light

**Comment by 5enseiii** [comment]
fixed

**Comment by 5enseiii** [comment]
auf emulator funktioniert es, im browser nicht

**Comment by 5enseiii** [comment]
fixed
