### ISSUE TITLE
Titel in der AppBar passt nicht zum Button

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [BogyMitutoyoCTL/BOGY-App-2023-04#26]
Bei allen Buttons im MainMenu kommt man im Anschluss auf ein Widget, das im Titel den gleichen Namen hat:

* New Timer --> New Timer
* Active Timers --> Aktive Timer (Übersetzung: siehe #21 )
* Settings --> Settings

Nur bei "My Timers" kommt man zu "Categories". Das ist verwirrend.

![grafik](https://user-images.githubusercontent.com/25632350/228554858-9a5e691a-49bc-4b18-8fd5-b0c96c895e86.png)

![grafik](https://user-images.githubusercontent.com/25632350/228554966-88e50faf-adf5-434f-a6eb-f6427868e72e.png)

**Comment by 5enseiii** [comment]
fixed. alle titel passen nun zum button
