### ISSUE TITLE
name of time stamp doesn´t fit

### ISSUE THREAD

**Issue by Kilianh07** [BogyMitutoyoCTL/BOGY-App-2023-04#27]
![Screenshot 2023-03-29 165159](https://user-images.githubusercontent.com/125502553/228578922-1dc38b17-5919-482e-b5e3-d5d5e24675a7.png)

**Comment by 5enseiii** [comment]
![Screenshot 2023-03-30 084843](https://user-images.githubusercontent.com/125492622/228752608-789944ba-c707-4784-a489-d7f76ba3801f.png)

fixed
